import Head from "next/head";
// import Link from "next/link"; // Remove this line
// import LoginPage from "~/organisms/loginPage/LoginPage";

export default function Home() {
  return (
    <>
      <Head>
        <title>Duoasl</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      {/* <LoginPage /> */}
    </>
  );
}
